// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqXeJpFcYMEmF6M2YeZhskyJcwDYDe13Q',
    appId: '1:825216648889:web:5a03cd95b0c541dc60fd68',
    messagingSenderId: '825216648889',
    projectId: 'chat-app-89c11',
    authDomain: 'chat-app-89c11.firebaseapp.com',
    storageBucket: 'chat-app-89c11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdm0_ckCXQo0IeJHRoSGJ8cwKQ9ZVYy58',
    appId: '1:825216648889:android:8c3ff8e42cca8c7360fd68',
    messagingSenderId: '825216648889',
    projectId: 'chat-app-89c11',
    storageBucket: 'chat-app-89c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATER32tdQKijl-T-rgCpeWXnV-k6yuoGM',
    appId: '1:825216648889:ios:59c264028400db7160fd68',
    messagingSenderId: '825216648889',
    projectId: 'chat-app-89c11',
    storageBucket: 'chat-app-89c11.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATER32tdQKijl-T-rgCpeWXnV-k6yuoGM',
    appId: '1:825216648889:ios:59c264028400db7160fd68',
    messagingSenderId: '825216648889',
    projectId: 'chat-app-89c11',
    storageBucket: 'chat-app-89c11.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqXeJpFcYMEmF6M2YeZhskyJcwDYDe13Q',
    appId: '1:825216648889:web:3890ff481de2d42360fd68',
    messagingSenderId: '825216648889',
    projectId: 'chat-app-89c11',
    authDomain: 'chat-app-89c11.firebaseapp.com',
    storageBucket: 'chat-app-89c11.firebasestorage.app',
  );
}
